name: iBoot64Patcher

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macOS:
    env:
      PROCURSUS: /opt/procursus
      PATH: /opt/procursus/bin:/opt/procursus/libexec/gnubin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Update Xcode
      id: Update-Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1.0'
    - name: macOS Build
      id: macOS-Build
      run: |
        /Users/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/mac-bootstrap.sh
        /Users/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/mac-build.sh
        /Users/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/mac-post.sh
    - name: Versioning
      id: Versioning
      uses: actions/upload-artifact@v4
      with:
        name: Versioning
        path: |
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/latest_build_sha.txt
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/latest_build_num.txt
    - name: macOS x86_64 RELEASE Archive
      id: macOS-x86_64-RELEASE-Archive
      uses: actions/upload-artifact@v4
      with:
        name: iBoot64Patcher-macOS-x86_64-RELEASE
        path: |
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/iBoot64Patcher-macOS-x86_64-*-RELEASE.tar.xz
    - name: macOS x86_64 DEBUG Archive
      id: macOS-x86_64-DEBUG-Archive
      uses: actions/upload-artifact@v4
      with:
        name: iBoot64Patcher-macOS-x86_64-DEBUG
        path: |
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/iBoot64Patcher-macOS-x86_64-*-DEBUG.tar.xz
    - name: macOS arm64 RELEASE Archive
      id: macOS-arm64-RELEASE-Archive
      uses: actions/upload-artifact@v4
      with:
        name: iBoot64Patcher-macOS-arm64-RELEASE
        path: |
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/iBoot64Patcher-macOS-arm64-*-RELEASE.tar.xz
    - name: macOS arm64 DEBUG Archive
      id: macOS-arm64-DEBUG-Archive
      uses: actions/upload-artifact@v4
      with:
        name: iBoot64Patcher-macOS-arm64-DEBUG
        path: |
          /Users/runner/work/iBoot64Patcher/iBoot64Patcher/iBoot64Patcher-macOS-arm64-*-DEBUG.tar.xz
